### ISSUE TITLE
Feature: support union

### ISSUE THREAD

**Issue by JulienLecoq** [theboxer/zod-search-params#2]
Add the ability to parse union.

**Comment by theboxer** [comment]
@JulienLecoq can you provide a sample schema and expected output please?

**Comment by theboxer** [comment]
Not sure if it's fixed after the most recent changes, or you have different use case, but the following works as expectd:

```ts
const schemaCustom = z.object({
      numberOrString: z.union([z.string(), z.number()]).catch(''),
    });
```   

Feel free to reopen with more details if the issue still exists.
